### ISSUE TITLE
Add option to change coverage files directory

### ISSUE THREAD

**Issue by guillaume86** [ppumkin/PrestoCoverage#21]
First of all thanks for this extension!

It would be nice to be able to change the directory that contains the coverage files (I would prefer to store them in my solution folder).
You could detect a .prestocoverage config file at the solution root and read some config values inside to allow different settings by project and sharing settings with source control.

**Comment by ppumkin** [comment]
Hi Thanks for feedback.
I could definitely do something like that.

**Comment by ppumkin** [comment]
You can change the watch folder and filter from version 1.16.6 from the OPTIONS menu.

Part of the work in the PR above is getting ready the configuration so it can be loaded from a json file in the current solution folder if present. This may have some interesting challenges since the extension loads before any project is loaded... and closing and re opening another project is going to be fun to handle.

**Comment by ppumkin** [comment]
I will close this as the primary objective has been done and create a new issue #28 for a settings file in the solution.
